# Indique que l'on veut utiliser SQLite et créer un fichier database.db à la racine
spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Le dialecte pour que Spring sache comment parler à SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Créer ou mettre à jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update